#!/bin/bash

# Download URL
DOWNLOAD_URL="https://raw.githubusercontent.com/pojntfx/documatio/main/documatio"
# File which contains the current version
VERSION_FILE="${HOME}/.documatio_version"
# Endpoint which returns the latest commit hash for pojde
COMMIT_HASH_ENDPOINT="https://api.github.com/repos/pojntfx/pojde/commits/main"

# Shows documatio usage information.
print_help() {
    case "$1" in
    "-h" | "--help")
        :
        ;;
    *)
        printf "Unknown command or argument \"${arg}\".\n\n"
        ;;
    esac

    echo "In goes Markdown, out come indexed HTML and PDF slides and documents.

Utility Commands:
build                               Build the files in the \`docs\` directory.
dev                                 Re-compile if a file in the \`docs\` directory changes.

Miscellaneous Commands:
upgrade                             Upgrade this tool.

For more information, please visit https://github.com/pojntfx/documatio#Usage."

    exit 0
}

# Handle the main commands
case $1 in
# Upgrade this tool.
upgrade)
    # Read the following lines into memory first so that replacing the script while it is running doesn't lead to issues
    {
        # Get the current version
        touch "${VERSION_FILE}"
        current_version="$(cat ${VERSION_FILE})"

        # Check the latest version by fetching the commit hash
        latest_version="$(curl -s -H 'Accept: application/vnd.github.VERSION.sha' ${COMMIT_HASH_ENDPOINT})"

        # Upgrade if the versions don't match
        if [ "${current_version}" != "${latest_version}" ]; then
            echo "Upgrading to version \"${latest_version}\" ..."

            # Fetch the latest version from GitHub
            sudo curl -L -o /usr/local/bin/documatio "${DOWNLOAD_URL}"

            # Make it executable
            sudo chmod +x /usr/local/bin/documatio

            # Add the new commit hash
            echo "${latest_version}" >"${VERSION_FILE}"

            # Exit to use the new script
            exit
        fi

        echo "No update available. You have version \"${current_version}\", the latest version is \"${latest_version}\"."

        exit
    }

    ;;

*)
    print_help $1
    ;;
esac
